# flutter version 3.37.3

name: story_box
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  #  get: ^4.6.6
  carousel_slider: ^5.0.0
  blurrycontainer: ^2.1.0
  lottie: ^3.1.3
  #  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  #  fluttertoast: ^8.2.8
  fluttertoast: ^8.2.12
  #  logger: ^2.4.0
  logger: ^2.5.0
  preload_page_view: ^0.2.0
  shimmer: ^3.0.0
  chewie: ^1.8.5
  video_player: ^2.9.5
  #  video_player: ^2.9.2
  readmore: ^3.0.0
  get_storage: ^2.1.1
  intl: ^0.20.2
  #  intl: ^0.19.0
  connectivity_plus: ^6.1.0
  http: ^1.4.0
  #  http: ^1.2.2
  firebase_core: ^3.13.0
  #  firebase_core: ^3.6.0
  firebase_auth: ^5.5.3
  #  firebase_auth: ^5.3.1
  firebase_messaging: ^15.2.5
  #  firebase_messaging: ^15.1.3
  device_info_plus: ^11.1.0
  google_sign_in: ^6.3.0
  #  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  #  sign_in_with_apple: ^6.1.3
  google_mobile_ads: ^6.0.0
  #  google_mobile_ads: ^5.2.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  rate_my_app: ^2.3.1
  #  rate_my_app: ^2.2.0
  shared_preferences:
  in_app_purchase: ^3.2.1
  #  in_app_purchase: ^3.0.5
  flutter_stripe: ^10.0.0
  #  flutter_stripe: ^11.3.0
  #  razorpay_flutter: ^1.3.6
  razorpay_flutter: ^1.4.0
  flutter_spinkit: ^5.2.1
  flutter_local_notifications: ^18.0.1
  firebase_analytics: ^11.4.6
  #  firebase_analytics: ^11.3.6
  flutter_branch_sdk: ^7.1.0
  #  flutter_branch_sdk: ^8.5.0
  dio:
  share_plus: ^11.0.0
  #  share_plus: ^10.1.3
  flutter_bounceable: ^1.2.0
  cupertino_icons: ^1.0.8
  #  cupertino_icons: ^1.0.6
  vibration: ^3.1.3
  #  vibration: ^2.0.1
  flutterwave_standard:
  loading_animation_widget: ^1.3.0
  clipboard: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
  #    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 800

